######### train MCTformer V1 ##########
python main.py --model deit_small_MCTformerV1_patch16_224 \
                --device cuda:1 \
                --batch-size 64 \
                --data-set VOC12 \
                --img-list voc12 \
                --data-path 'path of the PASCAL VOC 2012 dataset' \
                --layer-index 12 \
                --output_dir 'path for save the output file' \
                --finetune https://dl.fbaipublicfiles.com/deit/deit_small_patch16_224-cd65a155.pth

######### Generating class attention maps ##########
python main.py --model deit_small_MCTformerV1_patch16_224 \
                --data-set VOC12MS \
                --scales 1.0 \
                --img-list 'root_dir/CB-SCTC/voc12/' \
                --data-path 'path of the PASCAL VOC 2012 dataset' \
                --output_dir 'path for save the output file' \
                --resume 'path for checkpoint file' \
                --gen_attention_maps \
                --attention-type fused \
                --layer-index 3 \
                --visualize-cls-attn \
                --patch-attn-refine \
                --attention-dir 'path for attention maps file' \
                --cam-npy-dir 'path for cam npy file' \
                --out-crf 'path for crf file' \

######### Evaluating the generated class attention maps ##########
python evaluation.py --list 'root_dir/CB-SCTC/voc12/train_id.txt' \
                     --gt_dir 'path for augmented ground truth. eg. root_dir/VOC2012/SegmentationClassAug' \
                     --logfile 'path for logfile   eg. root_dir/eval_log.txt' \
                     --type npy \
                     --curve True \
                     --predict_dir 'path of predict dir(cam-npy-dir)' \
                     --comment "train set"


######### postprocess the generated class attention maps ##########
python psa/train_aff.py --weights res38_cls.pth \
                        --voc12_root 'path of the PASCAL VOC 2012 dataset' \
                        --la_crf_dir 'path for la_crf' \
                        --ha_crf_dir 'path for ha_crf' \


python psa/infer_aff.py --weights resnet38_aff.pth 'generated by psa/train_aff.py' \
                    --infer_list 'root_dir/psa/voc12/train_aug.txt' \
                    --cam_dir 'path of predict dir(cam-npy-dir)' \
                    --voc12_root 'path of the PASCAL VOC 2012 dataset' \
                    --out_rw 'path for the infer output' \

python evaluation.py --list voc12/train_aug_id.txt \
                     --gt_dir 'path for augmented ground truth. eg. root_dir/VOC2012/SegmentationClassAug' \
                     --logfile 'path for logfile   eg. root_dir/eval_log.txt' \
                     --type png \
                     --predict_dir 'path for the infer output(out_rw)' \
                     --comment "train set"

######### train segNet stage ##########
python seg/train_seg.py --network resnet38_seg \
                    --num_epochs 30 \
                    --seg_pgt_path 'path for the infer output(out_rw)' \
                    --init_weights res38_cls.pth \
                    --save_path  'path for the train output' \
                    --list_path voc12/train_aug_id.txt \
                    --img_path 'root_dir/VOC2012/JPEGImages/' \
                    --num_classes 21 \
                    --batch_size 4

python seg/infer_seg.py --weights 'eg. save_path/model_29.pth' \
                      --network resnet38_seg \
                      --list_path voc12/val_id.txt \
                      --gt_path 'path for augmented ground truth. eg. root_dir/VOC2012/SegmentationClassAug' \
                      --img_path 'root_dir/VOC2012/JPEGImages/' \
                      --save_path 'path for val_seg_crf' \
                      --save_path_c 'path for val_seg_crf_c' \
                      --scales 0.5 0.75 1.0 1.25 1.5 \
                      --use_crf True

python seg/infer_test_seg.py --weights 'eg. save_path/model_29.pth' \
                      --network resnet38_seg \
                      --list_path voc12/test_id.txt \
                      --img_path 'root_dir/VOC2012/JPEGImages/' \
                      --save_path 'path for test_seg_crf' \
                      --save_path_c 'path for test_seg_crf' \
                      --scales 0.5 0.75 1.0 1.25 1.5 \
                      --use_crf True