######### train MCTformer V1 ##########
python main.py --model deit_small_MCTformerV1_patch16_224 \
                --batch-size 64 \
                --data-set COCO \
                --img-list coco \
                --data-path 'path of the MS COCO 2014 dataset' \
                --layer-index 12 \
                --output_dir 'path for save the output file' \
                --label-file-path 'root_dir/COCO_cls_labels.npy' \
                --finetune https://dl.fbaipublicfiles.com/deit/deit_small_patch16_224-cd65a155.pth

######### Generating class-specific localization maps ##########
python main.py --model deit_small_MCTformerV1_patch16_224 \
                --data-set COCOMS \
                --scales 1.0 \
                --img-list coco \
                --data-path 'path of the MS COCO 2014 dataset' \
                --output_dir 'path for save the output file' \
                --resume 'path for checkpoint file' \
                --gen_attention_maps \
                --attention-type fused \
                --layer-index 3 \
                --visualize-cls-attn \
                --patch-attn-refine \
                --label-file-path COCO_cls_labels.npy \
                --attention-dir 'path for attention maps file' \
                --cam-npy-dir 'path for cam npy file' \
                --out-crf 'path for crf file'


######### Evaluating the generated class-specific localization maps ##########
python evaluationCoCo.py --list 'root_dir/CB-SCTC/coco/coco_train_labeled_list.txt' \
                     --gt_dir 'root_dir/datasets/COCO2014/train2014_annotations' \
                     --logfile 'path for logfile   eg. root_dir/eval_log.txt' \
                     --type npy \
                     --curve True \
                     --predict_dir 'path of predict dir(cam-npy-dir)' \
                     --comment "coco_train_labeled_list.txt"

######### postprocess the generated class attention maps ##########
python psa/train_aff.py --weights res38_cls.pth \
                        --voc12_root 'path of the MS COCO 2014 dataset' \
                        --train_list 'root_dir/coco/coco_train_labeled_list.txt' \
                        --val_list 'root_dir/coco/coco_val_labeled_list.txt' \
                        --la_crf_dir 'path for la_crf' \
                        --ha_crf_dir 'path for ha_crf' \


python psa/infer_aff.py --weights resnet38_aff.pth 'generated by psa/train_aff.py'\
                    --infer_list 'root_dir/coco/coco_train_labeled_list.txt' \
                    --cam_dir 'path of predict dir(cam-npy-dir)' \
                    --voc12_root 'path of the MS COCO 2014 dataset' \
                    --out_rw 'path for the infer output'

python evaluationCoCopng.py --list 'root_dir/coco/coco_train_labeled_list.txt' \
                     --gt_dir 'root_dir/datasets/COCO2014/train2014_annotations' \
                     --logfile 'path for logfile   eg. root_dir/eval_log.txt' \
                     --type png \
                     --predict_dir 'path for the infer output(out_rw)' \
                     --comment "coco_train_labeled_list.txt"

python seg/train_seg.py --network resnet38_seg \
                    --num_epochs 30 \
                    --seg_pgt_path 'path for the infer output(out_rw)' \
                    --init_weights res38_cls.pth \
                    --save_path  'path for the train output' \
                    --list_path 'root_dir/coco/coco_train_labeled_list.txt' \
                    --img_path 'root_dir/COCO2014/JPEGImages' \
                    --num_classes 81 \
                    --batch_size 4

python seg/infer_seg.py --weights 'eg. save_path/model_29.pth' \
                      --network resnet38_seg \
                      --list_path 'root_dir/CB-SCTC/coco/coco_val_labeled_list.txt' \
                      --gt_path 'root_dir//COCO2014/val2014_annotations' \
                      --img_path 'root_dir/COCO2014/JPEGImages/' \
                      --save_path 'path for coco_val_seg_crf' \
                      --save_path_c 'path for coco_val_seg_crf_c' \
                      --scales 0.5 0.75 1.0 1.25 1.5 \
                      --use_crf True\
                      --gpu_id 0


python seg/infer_seg_eval.py --weights 'eg. save_path/model_29.pth' \
                      --network resnet38_seg \
                      --list_path 'root_dir/CB-SCTC/coco/coco_val_labeled_list.txt' \
                      --gt_path 'root_dir//COCO2014/val2014_annotations' \
                      --img_path 'root_dir/COCO2014/JPEGImages/' \
                      --save_path 'path for coco_val_seg_crf' \
                      --save_path_c 'path for coco_val_seg_crf_c' \
                      --scales 0.5 0.75 1.0 1.25 1.5 \
                      --use_crf True\
                      --gpu_id 0